# version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception_net
    # healthcheck:
    #   test:
    #     [
    #       'CMD-SHELL',
    #       'mysql -u root -p$MYSQL_ROOT_PASSWORD -e ''SELECT User FROM mysql.user WHERE User="$MYSQL_USER";''',
    #     ]
    #   timeout: 30s
    #   retries: 20
    #   interval: 1s
  wordpress:
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_healthy
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - wp_data:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '443:443'
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
      - ssl_certs:/etc/nginx/ssl
    networks:
      - inception_net
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost']
    #   timeout: 30s
    #   retries: 20
    #   interval: 1s

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/yoka/data/db_data
      o: bind
      type: none
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/yoka/data/wp_data
      o: bind
      type: none
  ssl_certs:
    name: ssl_certs
    driver: local
    driver_opts:
      device: /home/yoka/data/ssl_certs
      o: bind
      type: none

networks:
  inception_net:
    driver: bridge
